name: multi-blog-monitoring

services:
  prometheus:
    image: prom/prometheus:v3.5.0
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=15d'
      - '--web.enable-lifecycle'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - '16686:16686'  # Jaeger UI
      - '4317:4317'    # OTLP gRPC receiver
      - '4318:4318'    # OTLP HTTP receiver
      - '14250:14250'  # Jaeger gRPC receiver (for legacy)
      - '14268:14268'  # Jaeger HTTP receiver (for legacy)
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_OTLP_GRPC_HOST_PORT=0.0.0.0:4317
      - COLLECTOR_OTLP_HTTP_HOST_PORT=0.0.0.0:4318
      - SPAN_STORAGE_TYPE=memory
    volumes:
      - jaeger_data:/tmp

volumes:
  prometheus_data:
  grafana_data:
  jaeger_data:
