global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Multi-blog API metrics
  - job_name: 'multi-blog-api'
    static_configs:
      - targets: ['host.docker.internal:9001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 8s
    fallback_scrape_protocol: 'PrometheusText0.0.4'

  # Add more targets here as your infrastructure grows
  # - job_name: 'node_exporter'
  #   static_configs:
  #     - targets: ['node_exporter:9100']
